version: "3.7"

services:
  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    ports:
      - ${DATABASE_PORT}:5432
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"
  back:
    container_name: back
    build: ./back
    restart: always
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA}
      DATABASE_REGION: ${DATABASE_REGION}
    volumes:
      - ./back:/app/back
      - ./common:/app/common
      - /app/back/node_modules
  front:
    container_name: front
    build: ./front
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app/front
      - ./common:/app/common
      - /app/front/node_modules
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
