version: "3.7"

services:
  front:
    container_name: front
    build: .
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/front/node_modules
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}